on:
  push:
    branches:
      - main
    paths:
      - assets/images/**


concurrency:
  group: normalize-file-names-${{ github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: 'bash'


jobs:
  node-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: node ./normalize-file-names.js

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Нормалізація імен файлів зображень"
          git push
